// src/lib/components/Rail.svelte
<script lang="ts">
	let { showResume = false, children } = $props();

	let translateClass = $derived(showResume === false ? 'translate-x-0' : '-translate-x-1/2');
</script>

<div
	class="{translateClass} flex h-screen max-h-screen w-[200vw] flex-row overflow-hidden transition-transform duration-700 ease-in-out"
>
	{@render children()}
</div>

// components/Rail.vue
<script setup lang="ts">
  const showResume = inject<Ref<boolean>>('showResume', ref(false));

  let translateClass: ComputedRef<string> = computed(() => 
    showResume?.value === false
      ? 'translate-x-0'
      : '-translate-x-1/2'
  );
</script>

<template>
  <div :class="[
    'w-[200vw] h-screen max-h-screen overflow-hidden flex flex-row transition-transform duration-700 ease-in-out',
    translateClass
  ]">
    <slot />
  </div>
</template>
