// src/lib/components/portfolio/index.svelte
<script lang="ts">
	import RailSide from '../RailSide.svelte';
	import Hero from './Hero.svelte';
	import Tagline from './Tagline.svelte';
	import Expertise from './Expertise.svelte';
	import ToolStack from './ToolStack.svelte';

	let { showResume = false, onUpdateShowResume } = $props();
</script>

<RailSide class="bg-zinc-900 text-zinc-100">
	<Hero {showResume} {onUpdateShowResume} />
	<Tagline />
	<Expertise />
	<ToolStack />
</RailSide>

// components/Portfolio/index.vue
<script setup lang="ts">
  type Props = {
    showResume?: boolean
  }
  withDefaults(defineProps<Props>(), { showResume: false });
  defineEmits([ 'updateShowResume' ]);
</script>

<template>
  <rail-side class="bg-zinc-900 text-zinc-100">
    <portfolio-hero
      :show-resume="showResume"
      @update-show-resume="(val: boolean) => $emit('updateShowResume', val)"
    />

    <portfolio-tagline />

    <portfolio-expertise />
  </rail-side>
</template>
